name: Update Localization

on:
  workflow_dispatch:
  push:

env:
  FLUTTER_VERSION: "3.24.5"

jobs:
  update_localization:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install dependencies
        working-directory: app
        run: flutter pub get

      - name: Run slang localization
        working-directory: app
        run: dart run slang

      - name: Commit localization changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add 。
          git commit -m "chore: Update localization files [skip ci]" || echo "No changes to commit"
          git push